## Optimize the Model

In [14]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("charity_data.csv")
application_df.head()

        EIN                                      NAME  ... ASK_AMT IS_SUCCESSFUL
0  10520599              BLUE KNIGHTS MOTORCYCLE CLUB  ...    5000             1
1  10531628    AMERICAN CHESAPEAKE CLUB CHARITABLE TR  ...  108590             1
2  10547893        ST CLOUD PROFESSIONAL FIREFIGHTERS  ...    5000             0
3  10553066            SOUTHSIDE ATHLETIC ASSOCIATION  ...    6692             1
4  10556103  GENETIC RESEARCH INSTITUTE OF THE DESERT  ...  142590             1

[5 rows x 12 columns]

In [15]:
#value counts for the status coolumn (to be dropped)
application_df["STATUS"].value_counts()

#value counts for the special considerations coolumn (to be dropped)
#application_df["SPECIAL_CONSIDERATIONS"].value_counts()

1    34294
0        5
Name: STATUS, dtype: int64

In [16]:
# Drop the non-beneficial EIN column
application_df = application_df.drop(["EIN"],1)
application_df = application_df.drop(["STATUS"],1)
application_df = application_df.drop(["SPECIAL_CONSIDERATIONS"],1)
application_df.head(2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  after removing the cwd from sys.path.

                                     NAME  ... IS_SUCCESSFUL
0            BLUE KNIGHTS MOTORCYCLE CLUB  ...             1
1  AMERICAN CHESAPEAKE CLUB CHARITABLE TR  ...             1

[2 rows x 9 columns]

In [17]:
# display the number of unique values
application_df.nunique()

NAME                19568
APPLICATION_TYPE       17
AFFILIATION             6
CLASSIFICATION         71
USE_CASE                5
ORGANIZATION            4
INCOME_AMT              9
ASK_AMT              8747
IS_SUCCESSFUL           2
dtype: int64

In [18]:
# Look at NAME value counts for binning
name_counts = application_df["NAME"].value_counts()

#  How many name counts are greater than 5?
name_counts[name_counts > 5]

PARENT BOOSTER USA INC                             1260
TOPS CLUB INC                                       765
UNITED STATES BOWLING CONGRESS INC                  700
WASHINGTON STATE UNIVERSITY                         492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC     408
                                                   ...
OLD OAK CLIFF CONSERVATION LEAGUE INC                 6
AMERICAN NEPHROLOGY NURSES ASSOCIATION                6
HUMBLE ISD EDUCATIONAL SUPPORT GROUPS INC             6
PROFESSIONAL LOADMASTER ASSOCIATION                   6
CBMC INC                                              6
Name: NAME, Length: 354, dtype: int64

In [19]:
# Determine which values to replace if counts are less than or equal to 5.
names_to_replace = list(name_counts[name_counts <= 5].index)

# Replace in dataframe
for app in names_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(app,"Other")
    
# Check to make sure binning was successful
application_df['NAME'].value_counts()

Other                                           20043
PARENT BOOSTER USA INC                           1260
TOPS CLUB INC                                     765
UNITED STATES BOWLING CONGRESS INC                700
WASHINGTON STATE UNIVERSITY                       492
                                                ...
HABITAT FOR HUMANITY INTERNATIONAL                  6
DAMAGE PREVENTION COUNCIL OF TEXAS                  6
FLEET RESERVE ASSOCIATION                           6
HUGH OBRIAN YOUTH LEADERSHIP                        6
INTERNATIONAL CONGRESS OF CHURCHES MINISTERS        6
Name: NAME, Length: 355, dtype: int64

In [20]:
# Look at APPLICATION_TYPE value counts for binning
application_counts = application_df["APPLICATION_TYPE"].value_counts()
application_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [21]:
# Determine which values to replace if application counts are less than 500
names_to_replace = list(name_counts[name_counts < 500].index)

# Replace in dataframe
for app in names_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")
    
# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [22]:
# Look at CLASSIFICATION value counts for binning
class_counts= application_df['CLASSIFICATION'].value_counts()
class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [25]:
# Determine which values to replace if counts are less than 1000
names_to_replace = list(name_counts[name_counts < 1000].index)

# Replace in dataframe
for app in names_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(app,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [26]:
# Generate our categorical variable lists
application_cat=application_df.dtypes[application_df.dtypes=="object"].index.tolist()
application_cat

['NAME',
 'APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT']

In [27]:
# perform one-hot encoding on the data
application_with_dummies_df = pd.get_dummies(application_df)
application_with_dummies_df.head(3)

   ASK_AMT  IS_SUCCESSFUL  ...  INCOME_AMT_50M+  INCOME_AMT_5M-10M
0     5000              1  ...                0                  0
1   108590              1  ...                0                  0
2     5000              0  ...                0                  0

[3 rows x 469 columns]

In [28]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
x = application_with_dummies_df.drop(['IS_SUCCESSFUL'], axis = 'columns').values
y = application_with_dummies_df['IS_SUCCESSFUL'].values

# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(x, y)

In [29]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [30]:
# Define the model - deep neural net
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  100
hidden_nodes_layer2 = 30
hidden_nodes_layer3 = 10

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="sigmoid"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="sigmoid"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 100)               46900

 dense_1 (Dense)             (None, 30)                3030

 dense_2 (Dense)             (None, 10)                310

 dense_3 (Dense)             (None, 1)                 11

=================================================================
Total params: 50,251
Trainable params: 50,251
Non-trainable params: 0
_________________________________________________________________

In [31]:
# Compile the model
nn.compile(loss = "binary_crossentropy", optimizer="adam",metrics=["accuracy"])

In [32]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=200)

Epoch 1/200
804/804 [==============================] - 6s 4ms/step - loss: 0.5170 - accuracy: 0.7626
Epoch 2/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4482 - accuracy: 0.7920
Epoch 3/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4362 - accuracy: 0.7952
Epoch 4/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4303 - accuracy: 0.7982
Epoch 5/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4268 - accuracy: 0.7975
Epoch 6/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4248 - accuracy: 0.7991
Epoch 7/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4229 - accuracy: 0.7996
Epoch 8/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4215 - accuracy: 0.7998
Epoch 9/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4205 - accuracy: 0.7995
Epoch 10/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4192 - accuracy: 0.7994
Epoch 11/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4175 - accuracy: 0.8006
Epoch 12/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4175 - accuracy: 0.8008
Epoch 13/200
804/804 [==============================] - 4s 5ms/step - loss: 0.4160 - accuracy: 0.8003
Epoch 14/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4159 - accuracy: 0.8010
Epoch 15/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4147 - accuracy: 0.8023
Epoch 16/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4141 - accuracy: 0.8011
Epoch 17/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4133 - accuracy: 0.8022
Epoch 18/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4126 - accuracy: 0.8021
Epoch 19/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4122 - accuracy: 0.8031
Epoch 20/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4113 - accuracy: 0.8029
Epoch 21/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4114 - accuracy: 0.8038
Epoch 22/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4106 - accuracy: 0.8032
Epoch 23/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4103 - accuracy: 0.8040
Epoch 24/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4097 - accuracy: 0.8033
Epoch 25/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4096 - accuracy: 0.8035
Epoch 26/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4089 - accuracy: 0.8048
Epoch 27/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4093 - accuracy: 0.8047
Epoch 28/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4082 - accuracy: 0.8046
Epoch 29/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4078 - accuracy: 0.8058
Epoch 30/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4078 - accuracy: 0.8048
Epoch 31/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4074 - accuracy: 0.8052
Epoch 32/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4071 - accuracy: 0.8046
Epoch 33/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4070 - accuracy: 0.8050
Epoch 34/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4067 - accuracy: 0.8063
Epoch 35/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4061 - accuracy: 0.8057
Epoch 36/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4056 - accuracy: 0.8052
Epoch 37/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4056 - accuracy: 0.8054
Epoch 38/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4053 - accuracy: 0.8056
Epoch 39/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4044 - accuracy: 0.8062
Epoch 40/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4044 - accuracy: 0.8067
Epoch 41/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4045 - accuracy: 0.8063
Epoch 42/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4046 - accuracy: 0.8066
Epoch 43/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4039 - accuracy: 0.8054
Epoch 44/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4037 - accuracy: 0.8059
Epoch 45/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4031 - accuracy: 0.8058
Epoch 46/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4037 - accuracy: 0.8068
Epoch 47/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4035 - accuracy: 0.8059
Epoch 48/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4028 - accuracy: 0.8078
Epoch 49/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4029 - accuracy: 0.8071
Epoch 50/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4026 - accuracy: 0.8070
Epoch 51/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4021 - accuracy: 0.8078
Epoch 52/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4025 - accuracy: 0.8069
Epoch 53/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4021 - accuracy: 0.8067
Epoch 54/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4018 - accuracy: 0.8080
Epoch 55/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4021 - accuracy: 0.8072
Epoch 56/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4016 - accuracy: 0.8067
Epoch 57/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4012 - accuracy: 0.8065
Epoch 58/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4017 - accuracy: 0.8084
Epoch 59/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4009 - accuracy: 0.8077
Epoch 60/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4010 - accuracy: 0.8068
Epoch 61/200
804/804 [==============================] - 4s 5ms/step - loss: 0.4002 - accuracy: 0.8077
Epoch 62/200
804/804 [==============================] - 4s 5ms/step - loss: 0.4004 - accuracy: 0.8077
Epoch 63/200
804/804 [==============================] - 4s 5ms/step - loss: 0.3999 - accuracy: 0.8073
Epoch 64/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4002 - accuracy: 0.8071
Epoch 65/200
804/804 [==============================] - 3s 4ms/step - loss: 0.4005 - accuracy: 0.8078
Epoch 66/200
804/804 [==============================] - 3s 3ms/step - loss: 0.4000 - accuracy: 0.8084
Epoch 67/200
804/804 [==============================] - 4s 5ms/step - loss: 0.4001 - accuracy: 0.8084
Epoch 68/200
804/804 [==============================] - 3s 4ms/step - loss: 0.3999 - accuracy: 0.8077
Epoch 69/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3996 - accuracy: 0.8084
Epoch 70/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3995 - accuracy: 0.8080
Epoch 71/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3995 - accuracy: 0.8088
Epoch 72/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3996 - accuracy: 0.8080
Epoch 73/200
804/804 [==============================] - 2s 2ms/step - loss: 0.3998 - accuracy: 0.8090
Epoch 74/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3998 - accuracy: 0.8080
Epoch 75/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3992 - accuracy: 0.8080
Epoch 76/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3991 - accuracy: 0.8078
Epoch 77/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3995 - accuracy: 0.8077
Epoch 78/200
804/804 [==============================] - 3s 3ms/step - loss: 0.3992 - accuracy: 0.8088
Epoch 79/200
804/804 [==============================] - 3s 3ms/step - loss: 0.3990 - accuracy: 0.8080
Epoch 80/200
804/804 [==============================] - 3s 4ms/step - loss: 0.3991 - accuracy: 0.8082
Epoch 81/200
804/804 [==============================] - 3s 4ms/step - loss: 0.3997 - accuracy: 0.8087
Epoch 82/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3991 - accuracy: 0.8093
Epoch 83/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3990 - accuracy: 0.8086
Epoch 84/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3993 - accuracy: 0.8083
Epoch 85/200
804/804 [==============================] - 4s 5ms/step - loss: 0.3988 - accuracy: 0.8086
Epoch 86/200
804/804 [==============================] - 4s 5ms/step - loss: 0.3985 - accuracy: 0.8086
Epoch 87/200
804/804 [==============================] - 3s 3ms/step - loss: 0.3989 - accuracy: 0.8086
Epoch 88/200
804/804 [==============================] - 3s 4ms/step - loss: 0.3983 - accuracy: 0.8083
Epoch 89/200
804/804 [==============================] - 4s 4ms/step - loss: 0.3984 - accuracy: 0.8088
Epoch 90/200
804/804 [==============================] - 4s 4ms/step - loss: 0.3981 - accuracy: 0.8087
Epoch 91/200
804/804 [==============================] - 4s 5ms/step - loss: 0.3981 - accuracy: 0.8087
Epoch 92/200
804/804 [==============================] - 3s 3ms/step - loss: 0.3983 - accuracy: 0.8091
Epoch 93/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3985 - accuracy: 0.8086
Epoch 94/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3985 - accuracy: 0.8072
Epoch 95/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3981 - accuracy: 0.8087
Epoch 96/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3983 - accuracy: 0.8085
Epoch 97/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3975 - accuracy: 0.8089
Epoch 98/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3976 - accuracy: 0.8090
Epoch 99/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3985 - accuracy: 0.8087
Epoch 100/200
804/804 [==============================] - 3s 3ms/step - loss: 0.3982 - accuracy: 0.8084
Epoch 101/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3981 - accuracy: 0.8089
Epoch 102/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3989 - accuracy: 0.8089
Epoch 103/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3981 - accuracy: 0.8095
Epoch 104/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3978 - accuracy: 0.8095
Epoch 105/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3979 - accuracy: 0.8094
Epoch 106/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3979 - accuracy: 0.8091
Epoch 107/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3981 - accuracy: 0.8091
Epoch 108/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3981 - accuracy: 0.8090
Epoch 109/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3978 - accuracy: 0.8093
Epoch 110/200
804/804 [==============================] - 3s 3ms/step - loss: 0.3978 - accuracy: 0.8085
Epoch 111/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3979 - accuracy: 0.8084
Epoch 112/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3974 - accuracy: 0.8089
Epoch 113/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3984 - accuracy: 0.8087
Epoch 114/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3977 - accuracy: 0.8092
Epoch 115/200
804/804 [==============================] - 2s 2ms/step - loss: 0.3974 - accuracy: 0.8099
Epoch 116/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3975 - accuracy: 0.8092
Epoch 117/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3975 - accuracy: 0.8096
Epoch 118/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3980 - accuracy: 0.8090
Epoch 119/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3974 - accuracy: 0.8096
Epoch 120/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3973 - accuracy: 0.8094
Epoch 121/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3975 - accuracy: 0.8089
Epoch 122/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3974 - accuracy: 0.8095
Epoch 123/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3972 - accuracy: 0.8084
Epoch 124/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3979 - accuracy: 0.8091
Epoch 125/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3975 - accuracy: 0.8084
Epoch 126/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3973 - accuracy: 0.8092
Epoch 127/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3973 - accuracy: 0.8093
Epoch 128/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3975 - accuracy: 0.8096
Epoch 129/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3981 - accuracy: 0.8093
Epoch 130/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3977 - accuracy: 0.8084
Epoch 131/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3972 - accuracy: 0.8095
Epoch 132/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3970 - accuracy: 0.8093
Epoch 133/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3969 - accuracy: 0.8098
Epoch 134/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3967 - accuracy: 0.8098
Epoch 135/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3967 - accuracy: 0.8098
Epoch 136/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3968 - accuracy: 0.8091
Epoch 137/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3969 - accuracy: 0.8092
Epoch 138/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3970 - accuracy: 0.8094
Epoch 139/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3967 - accuracy: 0.8100
Epoch 140/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3972 - accuracy: 0.8096
Epoch 141/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3970 - accuracy: 0.8089
Epoch 142/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3972 - accuracy: 0.8096
Epoch 143/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3971 - accuracy: 0.8097
Epoch 144/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3966 - accuracy: 0.8092
Epoch 145/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3967 - accuracy: 0.8098
Epoch 146/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3973 - accuracy: 0.8097
Epoch 147/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3977 - accuracy: 0.8096
Epoch 148/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3977 - accuracy: 0.8101
Epoch 149/200
804/804 [==============================] - 3s 3ms/step - loss: 0.3973 - accuracy: 0.8100
Epoch 150/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3977 - accuracy: 0.8092
Epoch 151/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3974 - accuracy: 0.8090
Epoch 152/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3973 - accuracy: 0.8097
Epoch 153/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3971 - accuracy: 0.8100
Epoch 154/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3975 - accuracy: 0.8094
Epoch 155/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3972 - accuracy: 0.8096
Epoch 156/200
804/804 [==============================] - 2s 2ms/step - loss: 0.3971 - accuracy: 0.8094
Epoch 157/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3973 - accuracy: 0.8099
Epoch 158/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3979 - accuracy: 0.8090
Epoch 159/200
804/804 [==============================] - 3s 3ms/step - loss: 0.3975 - accuracy: 0.8096
Epoch 160/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3972 - accuracy: 0.8094
Epoch 161/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3970 - accuracy: 0.8094
Epoch 162/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3975 - accuracy: 0.8092
Epoch 163/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3976 - accuracy: 0.8100
Epoch 164/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3974 - accuracy: 0.8094
Epoch 165/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3975 - accuracy: 0.8090
Epoch 166/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3970 - accuracy: 0.8099
Epoch 167/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3974 - accuracy: 0.8100
Epoch 168/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3969 - accuracy: 0.8090
Epoch 169/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3970 - accuracy: 0.8095
Epoch 170/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3973 - accuracy: 0.8089
Epoch 171/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3967 - accuracy: 0.8092
Epoch 172/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3968 - accuracy: 0.8104
Epoch 173/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3971 - accuracy: 0.8098
Epoch 174/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3969 - accuracy: 0.8097
Epoch 175/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3968 - accuracy: 0.8092
Epoch 176/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3969 - accuracy: 0.8096
Epoch 177/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3969 - accuracy: 0.8103
Epoch 178/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3967 - accuracy: 0.8100
Epoch 179/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3969 - accuracy: 0.8103
Epoch 180/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3967 - accuracy: 0.8099
Epoch 181/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3970 - accuracy: 0.8098
Epoch 182/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3973 - accuracy: 0.8092
Epoch 183/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3969 - accuracy: 0.8101
Epoch 184/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3973 - accuracy: 0.8095
Epoch 185/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3975 - accuracy: 0.8097
Epoch 186/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3972 - accuracy: 0.8098
Epoch 187/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3973 - accuracy: 0.8101
Epoch 188/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3968 - accuracy: 0.8099
Epoch 189/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3973 - accuracy: 0.8097
Epoch 190/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3974 - accuracy: 0.8093
Epoch 191/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3974 - accuracy: 0.8097
Epoch 192/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3971 - accuracy: 0.8099
Epoch 193/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3969 - accuracy: 0.8104
Epoch 194/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3972 - accuracy: 0.8099
Epoch 195/200
804/804 [==============================] - 2s 3ms/step - loss: 0.3972 - accuracy: 0.8101
Epoch 196/200

In [33]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.4587 - accuracy: 0.7882 - 557ms/epoch - 2ms/step
Loss: 0.4586735665798187, Accuracy: 0.7882215976715088

In [34]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity_Optimization.h5")

USE A RANDOM FOREST CLASSIFIER ON THE DATASET

In [35]:
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

In [36]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78)

# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

# Evaluate the model
y_pred = rf_model.predict(X_test_scaled)
print(f"RF model accuracy: {accuracy_score(y_test, y_pred)*100:.2f}")

RF model accuracy: 77.78